# Generated by Django 4.0 on 2022-01-20 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('SP', 'sports'), ('BO', 'books'), ('OT', 'other'), ('GA', 'games'), ('LA', 'Im too lazy for that')], default='LA', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('about', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
