# Generated by Django 4.0 on 2022-01-20 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
        ),
    ]
