# Generated by Django 4.0 on 2022-01-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('sports', 'sports'), ('books', 'books'), ('other', 'other'), ('games', 'games'), ('lazy ass', 'Im too lazy for that')], default='LA', max_length=15),
        ),
    ]
