# Generated by Django 4.0 on 2022-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('sports', 'sports'), ('books', 'books'), ('other', 'other'), ('games', 'games')], default='other', max_length=15),
        ),
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
