# Generated by Django 4.0 on 2022-01-24 18:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date_comment', models.DateTimeField(default=datetime.datetime.now)),
                ('text_comment', models.TextField()),
                ('auction_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction')),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.user')),
            ],
        ),
    ]
