# Generated by Django 4.0 on 2022-01-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auction_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_comment', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to='auctions.user'),
        ),
    ]
