# Generated by Django 4.0 on 2022-01-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auctions_list', models.ManyToManyField(blank=True, to='auctions.Auction')),
                ('author_watchlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.user')),
            ],
        ),
    ]
