# Generated by Django 4.0 on 2022-01-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_watchlist_auctions_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='author_watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorswatchlist', to='auctions.user'),
        ),
    ]
