# Generated by Django 4.0 on 2022-01-30 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_watchlist_author_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='auctions_list',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctions_list',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auctionswatchlist', to='auctions.auction'),
        ),
    ]
