# Generated by Django 4.0 on 2022-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_delete_image_auction_image_auction_title_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
